version: '3.4'
services:
  mysql_database:
    image: mysql:8.0.28
    container_name: mysql_database
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=${MYSQL_USER:?err}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - mysql_database_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - local

volumes:
  mysql_database_data:

networks:
  local:
    driver: bridge
